### ISSUE TITLE
ZHA and device: using device type on master doesn't work

### ISSUE THREAD

**Issue by controlcde** [custom-components/remote_homeassistant#123]
I'm using remote_homassistant for ZHA with a ConbeeII on a raspi3. My master HA instance doesn't know ZHA. Now I've paired a Hue dimmer switch to my remote instance with ZHA. The entity for power will be created on remote and after reload on master. But to use the 4 buttons I could create an automation on remote with
```
trigger:
  - device_id: 146d3094214d3c5d61069b92f9abcdef
    domain: zha
    platform: device
    type: remote_button_short_press
    subtype: turn_on
```
but not on master because the master doesn't know the device - only the created entity. How could I use the device on master?
