### ISSUE TITLE
remote device_tracker local zone handling

### ISSUE THREAD

**Issue by pejotigrek** [custom-components/remote_homeassistant#128]
I have two HA instances connected via remote_homeassistant component - let's call them LOCAL and REMOTE.
LOCAL = main instance
REMOTE = additional instance

there are device_tracker entities [people's phones], that are REMOTE only, but I want to see them in LOCAL, so I am "forwarding" them with the component. the issue is, that what's "home" for REMOTE is at least "not_home" for LOCAL ["not_home" or other, named zone] but the forwarded entity doesn't know that.

this is messing up with some automations and groups in LOCAL instance obviously.

**is there any chance for configuring the device_tracker "forwarding" in a way that it compares it's location with LOCAL zones and displays it accordingly, instead just displaying zone with REMOTE definitions?**

geez, I really hope I wrote it all clear enough.. it's much easier to tell about it, than write, especially when english isn't my first language ;)

**Comment by pejotigrek** [comment]
@LazyTarget, there has to be some kind of telepathic communication going on :D - yesterday I did some workaround that I'm testing now and seems it is fulfilling my needs, and it sounds similar to your idea, but as for now - without any dissapearing problems. so here's what I did a day ago:

0. for starters: let's say the "troublesome" zone is named "The Office". so on LOCAL the name is "The Office", but on REMOTE the place is just "home".
1. if needed - on REMOTE: configured same zones as on LOCAL. not all, but those that I'm interested in [minus "The Office" - it remains "home" on REMOTE]
2. along with the "normal" google maps device trackers on REMOTE, I made [mqtt device trackers](https://www.home-assistant.io/integrations/device_tracker.mqtt/) - as with some tricks it can be used as a _template device tracker_t:

```
device_tracker:
- platform: mqtt
  devices:
    phone_a: "device_tracker/phone_a"
    phone_b: "device_tracker/phone_b"
  qos: 1
  payload_home: "on"
  payload_not_home: "off"
```

then, I wrote a small automation which is setting the REMOTE location [zone] properly, automation on REMOTE:

```
automation:
- id: mqtt_tracking
  alias: mqtt_tracking
  initial_state: on
  mode: restart
  trigger:
  - platform: state
    entity_id: device_tracker.google_maps_XXX
    id: person_a
  - platform: state
    entity_id: device_tracker.google_maps_YYY
    id: person_b
  action:
  - service: mqtt.publish
    data:
      topic: "device_tracker/{{ trigger.id }}"
      payload_template: "{{ 'The Office' if trigger.to_state.state == 'home' else trigger.to_state.state }}"
```

3. configured remote connection on LOCAL, so the imported entities are prefixed with _office_ - so ` device_tracker.google_maps_XXX` becames `device_tracker.office_google_maps_XXX` etc.
4. in the person's settings on LOCAL I chose the corresponding `device_tracker.office_*` entity.

that's all. and because in the end - those persons are somehow "watched" in LOCAL instance too, every person is defined by few device_trackers. the location/zone of the person is taken from the most recent one, and it is kept on LOCAL during all reboots etc. thanks to being set in recorder's config.
