### ISSUE TITLE
No entities on main instance

### ISSUE THREAD

**Issue by Flipsoo** [custom-components/remote_homeassistant#149]
Hey there, know this has been addressed in several issues but non of the described solutions work for me. 
So i have a connection between HA Remote and HA Main as seen in the status which shows connected. But there are no Entities appearing neighter with secure on or off, nor while adding manuell instructions in config - im not looking for Entities in Integration where it shows only the connection status, which is connected all the time im looking at entities in the entities tab with my prefix but none appear. 

this config has worked for me the last past month but all of a sudden it stopped working and i cant figure out whats my problem. 
All hints are appreciated=) 

Greetings and sorry if i ask here something absolutly obvious but cant get my head around this

```
Version used: 3.5, Hassio 2021.10.2
config: 
remote_homeassistant:
  instances:
  - host: <duckdns.org> 
    port: 443
    secure: <TrueAndFalseUsed>
    verify_ssl: true
    access_token: <SuperSecretTokenFromRemoteHa>
    entity_prefix: "remote_"
    load_components:
    - sensor
    - binary_sensor
    - device_tracker
    - person
    - input_boolean
    include:
      domains:
      - sensor
      - binary_sensor
      - person
      entities:
      - binary_sensor.<MyDevicesAllDoubleCheckedIfAvailable>
    subscribe_events:
    - state_changed
```
