### ISSUE TITLE
Can 'remote' be a different network?

### ISSUE THREAD

**Issue by jchhenderson** [custom-components/remote_homeassistant#200]
Hi,

I am trying to monitor my mum's HA (which I manage) but it'd be easier for me to have a dash with her main stats in my HA.

Is this possible?  She is in a different location to me.  She has a Nabu Casa account so I can view her instance but it requires logging out of mine and logging into hers every time which is a pain.

**Comment by jchhenderson** [comment]
OK, I now know if can from [issue 87](https://github.com/custom-components/remote_homeassistant/issues/87) but I cannot get it working.

I have the following in my config:

```
remote_homeassistant:
  instances:
    - host: !secret remote_ha_access_url
      port: 443
      secure: true
      verify_ssl: true
      access_token: !secret remote_ha_access_token
      entity_prefix: "mum_"
      include:
        domains:
          - sensor
```

where `!secret remote_ha_access_url` is in the form xxxxxxxxxx..ui.nabu.casa
and `!secret remote_ha_access_token` exists in the remote instance
