### ISSUE TITLE
Local custom switch using a remote switch

### ISSUE THREAD

**Issue by jvcsw** [custom-components/remote_homeassistant#205]
Hi everyone,

I'm trying to create a local switch (template) with a remote smart plug, but i can't get it to work.

I understand that when it is created, the remote plug entity does not yet exist.

Any ideas? Thanks

```
switch:
  - platform: template
    switches:
      nas:
        friendly_name: NAS
        unique_id: "nas"
        value_template: '{{ states. switch.remote_plug_nas.state }}'
        turn_on:
          service: switch.turn_on
          entity_id: switch.remote_plug_nas
        turn_off:
          service: switch.turn_off
          entity_id: switch.remote_plug_nas
```
