### ISSUE TITLE
[Support]  Trying to enable Zigbee services on Main instance that Remote Instance uses

### ISSUE THREAD

**Issue by Ryu945** [custom-components/remote_homeassistant#217]
```
remote_homeassistant:
  instances:
  - host: <ip of remote instance>
    load_components:
    - zigbee
```

I added this line to configuration.yaml on the main instance.  I get this error message.

`required key not provided @ data['remote_homeassistant']['instances'][0]['access_token']. Got None. (See /config/configuration.yaml, line 19).` 

The instances are already linked up with each other.
