### ISSUE TITLE
Is forwarding of keyboard_remote events possible ?

### ISSUE THREAD

**Issue by madbrain76** [custom-components/remote_homeassistant#256]
I setup a remote node with an FLIRC USB infrared receiver. This is a device that receives IR signals and outputs keystrokes (emulates a USB keyboard). I got the device to work in a remote HAOS node. I can trigger an automation from IR this way :

```
alias: Test keyboard remote
description: ""
trigger:
  - platform: event
    event_type: keyboard_remote_command_received
    event_data:
      device_name: flirc.tv flirc Keyboard
      key_code: 2
condition: []
action: []
mode: single
```

Is it possible to receive this event from my main node, and use them in an automation ? If so, how is the forwarding done ?

Also, I don't know if I setup the main/remote node connectivity correctly. There is no sharing of devices/entities going on whatsoever, which can't be right. Yet the sensor for the remote node shows "connected" state. What could I be missing ? I did RTFM.
