### ISSUE TITLE
weather forecasts are not fully forwarded to main instance.

### ISSUE THREAD

**Issue by marcelhoogantink** [custom-components/remote_homeassistant#285]
Looking at weather results in the main and remote HA-sites I found that forecast are not forwarded: 

Screenshot Remote, data from integration:
![image](https://github.com/custom-components/remote_homeassistant/assets/51886888/be0692a7-d67f-4f5b-9893-76858f25f043)

Screenshot Main, data from Remote:
![image](https://github.com/custom-components/remote_homeassistant/assets/51886888/e586f18a-e084-45b6-bf08-1ab43d8d3a6e)

Screenshot Main, data from integration:
![image](https://github.com/custom-components/remote_homeassistant/assets/51886888/3826dca9-927a-4338-bcd4-9731fce3dd2f)

As you can see, the lower daily and hourly forecast is not available in the remote data

**Comment by genehand** [comment]
Hey I figured out a workaround for this although it takes a little work. If you're interested:

### On the instance with the weather entity

Create a template sensor and put the forecasts in attributes (they're too big to be stored as a state).  With [triggers & action data](https://www.home-assistant.io/integrations/template/#trigger-based-handling-of-action-response-data) we can call `weather.get_forecasts`. Share this new entity with the other HA instance.

```yaml
- trigger:
    - platform: event
      event_type: event_template_reloaded
    - platform: state
      entity_id:
        - weather.pirateweather
  action:
    - service: weather.get_forecasts
      data:
        type: daily
      target:
        entity_id: weather.pirateweather
      response_variable: daily
    - service: weather.get_forecasts
      data:
        type: hourly
      target:
        entity_id: weather.pirateweather
      response_variable: hourly
  sensor:
    - name: Weather forecasts
      state: "{{ states('weather.pirateweather') }}"
      attributes:
        daily: "{{ daily['weather.pirateweather'].forecast }}"
        hourly: "{{ hourly['weather.pirateweather'].forecast }}"
```

### On the other instance

Create a template weather entity on the second instance, referencing those attributes:

```yaml
- trigger:
    - platform: event
      event_type: event_template_reloaded
    - platform: state
      entity_id:
        - sensor.weather_forecasts
  weather:
    name: Pirateweather
    condition_template: "{{ states('sensor.weather_forecasts') }}"
    forecast_daily_template: "{{ state_attr('sensor.weather_forecasts', 'daily') }}"
    forecast_hourly_template: "{{ state_attr('sensor.weather_forecasts', 'hourly') }}"
```

Note there appears to be some caching of the forecast data. If you're making changes and don't see it showing up, try it with a new entity name or by removing and recreating it.  I almost gave up before I realized :)

## On both instances

I recommend excluding the `sensor.weather_forecasts` entity from the recorder on both.  The forecast data takes a lot of room in the db and I believe is the main reason they moved it to the action method instead.
