### ISSUE TITLE
Connection to 2 remote instances not working, only one or the other connects

### ISSUE THREAD

**Issue by rkpatel33** [custom-components/remote_homeassistant#306]
Hi,

I have one central node on a Digital Ocean droplet running, with to remote local instances in each location I have. The DO droplet and the remote instances are connected via WireGuard tunnels and everything works well, including a proxy server to get to all the instances.

When I try to connect the main to 2 remote, it will only connect to one.  I have verified that both instances _can_ be connected to by commenting one out at a time, but together it seems to default to the first one on the list.

Wondering if you might have an idea here. Am going to try to debug this in the code but not sure of a good workflow for it.

```yaml
  instances:
    # NYC
    - host: 10.222.0.2
      port: 8123
      secure: false
      verify_ssl: false
      access_token: !secret access_token_hassnyc
      entity_prefix: "hassnyc_"
      # entity_friendly_name_prefix: ""
    # Anchorage
    - host: 10.222.0.3
      port: 8123
      secure: false
      verify_ssl: false
      access_token: !secret access_token_hassla
      entity_prefix: "hassla_"
      # entity_friendly_name_prefix: "
```
