### ISSUE TITLE
Toggle a switch on master is not working

### ISSUE THREAD

**Issue by CasparTheBridge** [custom-components/remote_homeassistant#32]
I have a remote HASS.IO installation with a usb Z-Wave stick and some nodes. I see all the data correct in the master.
But when I try to switch on or off a z-wave device from the master nothing happens..

What can be wrong?
I think I don't see anything in a log-file but maybe I'm checking the correct log-file?

**Comment by mrmaceurope** [comment]
Hi Casper,

Try sharing your configuration and filters for HA remote?

**Comment by jfrux** [comment]
@CasparTheBridge This happens to me whenever I restart the instance with the z-wave controller but do not restart the master instance.

I really do wish this could reconnect and "rediscover" / report properly that it cannot communicate with devices.

Even if it occasionally did some sort of check to verify its connection...

or even report if it cannot connect properly.

**Comment by CasparTheBridge** [comment]
> Hi Casper,
> 
> Try sharing your configuration and filters for HA remote?

This is what is in my config for remote homeassistant:
```
remote_homeassistant:
  instances:
  - host: 32.0.0.3
    port: 8123
    access_token: !secret meterhass_token
    entity_prefix: "MeterHASS_"
    exclude:
      domains:
      - automation
      - group
      - person
      entities:
      - automation.hass_restart_binary_sensor_automation_toggle
      - automation.mqtt_discovery_binary_sensor_creator
      - automation.mqtt_discovery_light_creator
      - automation.mqtt_discovery_sensor_creator
      - automation.mqtt_discovery_switch_creator
      # Same name as master instance
      - binary_sensor.updater
      - sensor.disk_free
      - sensor.disk_use_percent
      - sensor.last_boot
      - sensor.memory_free
      - sensor.memory_use_percent
      - sensor.processor_use
      - sensor.swap_use_percent
      # Not working / unused
      - sensor.long_power_failure_count
      - sensor.power_consumption_phase_l1
      - sensor.power_consumption_phase_l2
      - sensor.power_consumption_phase_l3
      - sensor.power_production_phase_l1
      - sensor.power_production_phase_l2
      - sensor.power_production_phase_l3
      - sensor.voltage_phase_l1
      - sensor.voltage_phase_l2
      - sensor.voltage_phase_l3
      - sensor.voltage_sags_phase_l1
      - sensor.voltage_sags_phase_l2
      - sensor.voltage_sags_phase_l3
      - sensor.voltage_swells_phase_l1
      - sensor.voltage_swells_phase_l2
      - sensor.voltage_swells_phase_l3
```

**Comment by mrmaceurope** [comment]
You need to added the ones in BOLD

`instances:
- host: 192.168.x.x
  port: 8123
  secure: false
  verify_ssl: false
  access_token: 
  entity_prefix: "f38s_"
  subscribe_events:
  **- zwave.network_ready
  - zwave.node_event
  - zwave.scene_activated
  - state_changed
  - service_registered**
  include:
    domains:
    - light
    - sensor
    - switch
    - binary_sensor
    - device_tracker
    - zwave`

**Comment by CasparTheBridge** [comment]
Thank you for the quick reply!

I've added the code but unfortunately it's still not working:
```
# Remote MeterHASS
remote_homeassistant:
  instances:
  - host: x.x.x.x
    port: 8123
    access_token: !secret meterhass_token
    entity_prefix: "MeterHASS_"
    subscribe_events:
    - zwave.network_ready
    - zwave.node_event
    - zwave.scene_activated
    - state_changed
    - service_registered
    exclude:
      domains:
      - automation
      - group
      - person
      entities:
      - automation.hass_restart_binary_sensor_automation_toggle
      - automation.mqtt_discovery_binary_sensor_creator
      - automation.mqtt_discovery_light_creator
      - automation.mqtt_discovery_sensor_creator
      - automation.mqtt_discovery_switch_creator
      # Same name as master instance
      - binary_sensor.updater
      - sensor.disk_free
      - sensor.disk_use_percent
      - sensor.last_boot
      - sensor.memory_free
      - sensor.memory_use_percent
      - sensor.processor_use
      - sensor.swap_use_percent
      # Not working / unused
      - sensor.long_power_failure_count
      - sensor.power_consumption_phase_l1
      - sensor.power_consumption_phase_l2
      - sensor.power_consumption_phase_l3
      - sensor.power_production_phase_l1
      - sensor.power_production_phase_l2
      - sensor.power_production_phase_l3
      - sensor.voltage_phase_l1
      - sensor.voltage_phase_l2
      - sensor.voltage_phase_l3
      - sensor.voltage_sags_phase_l1
      - sensor.voltage_sags_phase_l2
      - sensor.voltage_sags_phase_l3
      - sensor.voltage_swells_phase_l1
      - sensor.voltage_swells_phase_l2
      - sensor.voltage_swells_phase_l3
```

**Comment by CasparTheBridge** [comment]
> @CasparTheBridge This happens to me whenever I restart the instance with the z-wave controller but do not restart the master instance.
> 
> I really do wish this could reconnect and "rediscover" / report properly that it cannot communicate with devices.
> 
> Even if it occasionally did some sort of check to verify its connection...
> 
> or even report if it cannot connect properly.
> 
> If you change the log level in hass to info or debug you will see issues thrown by `home-assistant-remote` component.
> ![image](https://user-images.githubusercontent.com/171077/71980723-c5478e80-31ee-11ea-910c-d44ed39e412b.png)
> 
> @lukas-hetzenecker Is it possible we've had a regression from (#3) in the components ability to reconnect to configured remote instances when they temporarily go offline and then return? Looking through the code, I'm not sure I saw if there is a timeframe of which it stops trying to reconnect or not. Maybe a configurable timeout setting or something is in order. And maybe an installed sensor with the component that reports the state of instances based on their configured name in the config (also a potential new feature)... just a thought.

I did a few tests but it never works, I tried all kinds of booting sequences of master and remote. But switching from master is never working. And I never see anything in the logs.

**Comment by jfrux** [comment]
It almost sounds as if something is wrong on your remote instance... maybe connection issues... hmm

**Comment by CasparTheBridge** [comment]
To run the remote HASS.io as lean as possible my configuration.yaml is like this:
```
# Configure a default setup of Home Assistant (frontend, api, etc)
#default_config:
config:
frontend:
system_health:
updater:

# Additional platforms for remote connecion
http:
websocket_api:

# Z-Wave platform
zwave:
  usb_path: /dev/serial/by-id/usb-0658_0200-if00

# MQTT on VlasakkerHA
mqtt:
  broker: x.x.x.x
  username: !secret mqtt_username
  password: !secret mqtt_password
  client_id: home-assistant

# Sensor platform (all combined)
sensor:
  # System Monitor raspberry Pi
  - platform: systemmonitor
    resources:
      - type: disk_free
        arg: /
      - type: disk_use_percent
        arg: /
      - type: memory_free
      - type: memory_use_percent
      - type: swap_use_percent
      - type: processor_use
      - type: last_boot
  # Track current connections via Websocket API
  - platform: websocket_api
  # DSMR or Slimme meter (P1)
  - platform: dsmr
    port: /dev/serial/by-id/usb-FTDI_TTL232R_FTUAZN1W-if00-port0
```

**Comment by jfrux** [comment]
Stopped using Hass.io... had too many stability issues.
When I use HomeAssistant with docker-compose it's so effing fast.  I don't know why Hass.io is so slow.

It's slow to boot, hard to keep stable, Tried Raspberry Pi and VirtualBox on real hardware... all of them seem to end up getting to where they don't restart quick enough and are just unwieldy.

I think it's the way it's trying to containerize things...

HomeAssistant running in a docker container by itself is so zippy.

Still going to try home-assistant-remote but in docker-compose style setup.

**Comment by CasparTheBridge** [comment]
I still haven't found why the switch functions is not working. Getting information from the slave is working fine but writing information to the slave doesn't seem to work. Not for a dimmer, not for a switch and also not for non-Zwave related hardware.

Any suggestions in how I can see more what can probably point to the issue? Where can I increase the log-level?

**Comment by ThePirat91** [comment]
Same problem of @CasparTheBridge here with hassio 0.109.6 and remote-homeassistant 2.1....
I can see the status of slave entities on my master instance but I cannot change anything on the slave from master....

**Comment by Gerfunky** [comment]
Ive had the same problem i narrowed it down to the setting entity_prefix:
if i remove the setting everything works i can controll the slave from the master but with the setting i get an error in the log.

**Comment by postlund** [comment]
Anyone with the base problem that could provide debug logs when flipping a switch when it doesn't work? If it works without entity prefix but not with, we probably don't strip the prefix properly somewhere before sending it to the remote instance. Would like to figure out where.

**Comment by CasparTheBridge** [comment]
> Anyone with the base problem that could provide debug logs when flipping a switch when it doesn't work? If it works without entity prefix but not with, we probably don't strip the prefix properly somewhere before sending it to the remote instance. Would like to figure out where.

Which logs would you like to have and do I have to change the debug level?

**Comment by postlund** [comment]
> > Anyone with the base problem that could provide debug logs when flipping a switch when it doesn't work? If it works without entity prefix but not with, we probably don't strip the prefix properly somewhere before sending it to the remote instance. Would like to figure out where.
> 
> Which logs would you like to have and do I have to change the debug level?

We can start with logs for this component:

```yaml
logger:
  default: warning
  logs:
    homeassistant.components.remote_homeassistant: debug
```
