### ISSUE TITLE
Exclude all?

### ISSUE THREAD

**Issue by bditter** [custom-components/remote_homeassistant#329]
Is there a way to exclude all entities by default instead of having all entries for a domain pulled in?

I just need one or two sensors but when I switch the binary_sensor domain from excluded to included it pulls in all 6000 of my sensors. 

It would be beneficial if the configuration could be set to exclude all and only include the entities that you want.

I did try adding the individual sensors to the include with the binary_sensor domain excluded and the entities never appeared.

**Comment by poudenes** [comment]
Would be great when you use

```
    include:
      entities:
      - zwave.controller
      - zwave.desk_light
```

Then only those 2 entities will be added.

```
    include:
      domains:
      - sensor
      entities:
      - zwave.controller
      - zwave.desk_light
```

Only 2 entities and the domain sensor will added.

Nothing more.

```
    exclude:
      domains:
      - light
      entities:
      - group.all_switches
```

This one will exclude everything in domain and only 1 entities

I tried only use the first option to include 2 entities. But It was added everything from my main HA
