### ISSUE TITLE
bi-directional use?

### ISSUE THREAD

**Issue by Flipsoo** [custom-components/remote_homeassistant#40]
Hello,
Ive tried to get a setup running where 2 instances of hassio connect together, but while i have to restart one instance to get the custom component running, the second instance only has the entities but doesnt get new state changes - the one last rebooted works great but the other doesnt.
is there a trick or something in the readme im missing for that behavior? 

Greetings to all of you:)

**Comment by marc-romu** [comment]
I've tried to connect two instances of home assistant together with *remote_homeassistant* version 3.1. My configuration is something like this:

##### Instance 1
```
remote_homeassistant:
  instances:
  - host: 192.168.10.1
    port: 8123
    entity_prefix: "ha2_"
    access_token: !secret access_token_to_2
    verify_ssl: false
    secure: false
    include:
      entities:
      - sensor.indoor_temperature
      - sensor.indoor_humidity
      - sensor.indoor_co2
      - light.bedroom
    subscribe_events:
      - state_changed
      - service_registered
      - mobile_app_notification_action
```
##### Instance 2
```
remote_homeassistant:
  instances:
  - host: 192.168.20.1
    port: 8123
    entity_prefix: "ha1_"
    access_token: !secret access_token_to_1
    verify_ssl: false
    secure: false
    include:
      entities:
      - sensor.downstairs_temperature
      - sensor.upstairs_temperature
```
### Problem
While one instance is stopped or being restarted, the other one works fine.
When both instances are running, UI heavily decreases performance and it's almost impossible to interact with.
I haven't been able to see what happens in live because both instances get collapsed and I cannot see any relevant error or warning in logs. I think it could be happening something like this:
- Instance 1 updates some sensor
- Instance 2 is listening to event ``state_changed`` on instance 1, so it updates sensors
- Instance 1 is listening to event ``state_changed`` on instance 2, so it updates sensors
- Instance 2 is listening to event ``state_changed`` on instance 1, so it updates sensors
- (and it gets stuck in a loop)

I've tried to disable subscription to ```state_changed``` and ```service_registered``` on instance 1 and now there is no performance decrease, but sensors are not updated either.

```
    subscribe_events:
#      - state_changed
#      - service_registered
      - mobile_app_notification_action
```

Is there any known solution for it? Thanks!
