### ISSUE TITLE
Not able to make home-assistant-remote work

### ISSUE THREAD

**Issue by ygreq** [custom-components/remote_homeassistant#42]
Hi guys, 

I am trying to figure out what to do in order to make the addon functional in my setup. Do you have any clues on why it does not work? Thank you so much for all your help. This is what I did:

-I checked that I can access both HA instances from outside of the network. (I did this with the help of ZeroTier One. Both are in the same virtual network now along with a laptop from where I can access them. From my laptop I can ping both HA instances and I can also access them in the browser by going to their IP address as created in ZeroTier One)
-I installed HACS on both HA devices and installed remote_homeassistant in HACS
-I created an access token in the remote instance of HA. 
-In the remote HA instance (I called ggs) in the configuration.yaml file I only added `remote_homeassistant:`
-in the main HA instance (I called home) in the configuration.yaml file I added the following:
```
remote_homeassistant:
   instances:
   - host: [IP_ADDRESS_of_REMOTE_Instance_provided_by_ZEROTIER_ONE]
     port: 8123
     secure: false
     verify_ssl: true
     access_token: !secret ggs_access_token
     entity_prefix: "ggs_"

```

What else should I do?
Thank you once again for any help you can provide!
ygr

**Comment by lukas-hetzenecker** [comment]
Hello,

this looks actually correct.
The remote instances don't need to have remote_homeassistant installed (clarified that in the instructions now), but it shouldn't hurt either.
Do you see any error messages in "Developer Tools - Logs" in the web UI of the primary instance?

**Comment by ygreq** [comment]
Hi, Lukas! Sorry it took so much to answer. I had to restart the remote host. 

This is what is says in the log: 

Log Details (ERROR)
Logger: custom_components.remote_homeassistant
Source: custom_components/remote_homeassistant/__init__.py:176
First occurred: 6:03:34 PM (144 occurrences)
Last logged: 6:28:10 PM

Could not connect to ws://[REMOTE_HOST_IP_via_ZEROTIER]:8123/api/websocket, retry in 10 seconds...

Any ideas what it means? BTW, I still can connect to it via my extra pc (which is the 3rd device in the ZeroTier virtual network, but also in the same physical network with the main HA instance. First is the main HA instance on a Proxmox, Second is the remote HA instance on a Raspberry 3B+)

**Comment by ygreq** [comment]
Hi Lukas! Did you have a chance to look into this? Do you know what I should do?

Thank you so much!

**Comment by ygreq** [comment]
I just tested the setup on the same network. I modified the IP address in the configuration.yaml to reflect the changes. Now I have: 

```
remote_homeassistant:
  instances:
  - host: 192.168.1.101
    port: 8123
    access_token: !secret ggs_same_network_access_token
    entity_prefix: "ggs_"

```

I still get the error:

> Logger: custom_components.remote_homeassistant
> Source: custom_components/remote_homeassistant/__init__.py:176
> First occurred: 3:50:10 PM (32 occurrences)
> Last logged: 3:55:20 PM
> 
> Could not connect to ws://192.168.1.101:8123/api/websocket, retry in 10 seconds...

I also tried using   - host: https://192.168.1.101. Still nothing

Please help! :(
